# Planner selection
base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 20.0
planner_patience: 5.0
controller_patience: 5.0
conservative_reset_dist: 3.0
recovery_behavior_enable: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 5.0
oscillation_distance: 0.5
max_planning_retries: -1

# Global planner
NavfnROS:
  allow_unknown: true
  default_tolerance: 0.0
  planner_window_x: 0.5
  planner_window_y: 0.5
  visualize_potential: false

# Local planner
DWAPlannerROS:
  acc_lim_x: 10.0
  acc_lim_y: 10.0
  acc_lim_theta: 10.0

  max_trans_vel: 2.0
  min_trans_vel: 0.1
  max_rot_vel: 2.0
  min_rot_vel: 0.4

  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_y: 2.0
  min_vel_y: 0.0

  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: false

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 10
  vth_samples: 20
  controller_frequency: 20.0

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

  oscillation_reset_dist: 0.05

  prune_plan: true
